language: android
dist: trusty
sudo: required

android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-29
    - extra-android-m2repository
    - android-$ANDROID_API_LEVEL
    # sys-img-armeabi-v7a-google_apis-25
    - sys-img-$ANDROID_ABI-android-$ANDROID_API_LEVEL

before_script:
  # - android list sdk --extended --no-ui --all
  - chmod +x gradlew      # Grant permissions

script:
  - ./gradlew buildDebug buildRelease

notifications:
  email: false