language: android
dist: trusty

env:
  matrix:
    - ANDROID_API_LEVEL=21 ANDROID_ABI=armeabi-v7a
    - ANDROID_API_LEVEL=23 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=5

android:
  components:
    - build-tools-29.0.3
    - android-29
    - extra-android-m2repository
    - android-$ANDROID_API_LEVEL
    # sys-img-armeabi-v7a-google_apis-25
    - sys-img-$ANDROID_ABI-android-$ANDROID_API_LEVEL

before_script:
  # - android list sdk --extended --no-ui --all
  - chmod +x gradlew      # Grant permissions

script:
  - ./gradlew buildDevelopmentDebug buildDevelopmentRelease
  - ./gradlew testDevelopmentDebug createDevelopmentDebugUnitTestCoverageReport assembleAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false