version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    working_directory: ~/Training_Task_1
    docker:
      - image: circleci/android:api-28
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - run:
        name: Run Lint
        command: ./gradlew lint
      - run:
        name: Run Build
        command: ./gradlew build
