version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    working_directory: ~/Training_Task_1
    docker:
      - image: circleci/android:api-28
    environment:
      CODECOV_TOKEN: 25ac4cf4-39e2-4b79-95bd-97528e01d98a
    steps:
      - checkout
      - run:
          name: Change Permission
          command: chmod +x gradlew
      - run:
          name: Run Lint.
          command: ./gradlew lint
      - run:
          name: Run Build
          command: ./gradlew build
      - run:
          name: Create Coverage Report
          command: ./gradlew jacocoTestReport
      - run:
          name: Run CodeCov
          command: bash <(curl -s https://codecov.io/bash)