version: 2.1

orbs:
 android: circleci/android@0.2.0

language: java
sudo: false

jobs:
  build:
    working_directory: ~/Training_Task_1
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx4g
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - checkout
      - run:
          name: Change Permission
          command: chmod +x gradlew
      - run:
          name: Clean Project
          command: ./gradlew clean
      - run:
          name: Run Lint
          command: ./gradlew lintDevelopmentDebug lintDevelopmentRelease
      - run:
          name: Run Build
          command: ./gradlew buildDevelopmentDebug buildDevelopmentRelease
