version: 2.1

orbs:
 android: circleci/android@0.2.0

language: java
sudo: false

jobs:
  build:
    working_directory: ~/Training_Task_1
    docker:
      - image: circleci/android:api-28
    environment:
      CODECOV_TOKEN: 25ac4cf4-39e2-4b79-95bd-97528e01d98a
      JVM_OPTS: -Xmx4g
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - checkout
      - run:
          name: Change Permission
          command: chmod +x gradlew
      - run:
          name: Run Lint
          command: ./gradlew lintDevelopmentDebug lintDevelopmentRelease
      - run:
          name: Run Build + Coverage Report
          command: ./gradlew buildDevelopmentDebug buildDevelopmentRelease createDevelopmentDebugUnitTestCoverageReport
      - run:
          name: Renaming folder and files of reports so codecov.io can find it One
          command: mv app/build/reports/jacoco/createDevelopmentDebugUnitTestCoverageReport app/build/reports/jacoco/jacocoTestDevelopmentDebugUnitTestReport
      - run:
          name: Renaming folder and files of reports so codecov.io can find it TWO
          command: mv app/build/reports/jacoco/jacocoTestDevelopmentDebugUnitTestReport/createDevelopmentDebugUnitTestCoverageReport.xml app/build/reports/jacoco/jacocoTestDevelopmentDebugUnitTestReport/jacocoTestDevelopmentDebugUnitTestReport.xml
      - run:
          name: Run CodeCov
          command: bash <(curl -s https://codecov.io/bash)
