version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    working_directory: ~/Training_Task_1
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - run:
          name: Change permission
          command: chmod +x gradlew
      - run:
          name: Run Lint
          command: ./gradlew lint
      - run:
          name: Run Build
          command: ./gradlew build
